# Prometheus Configuration

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'secustreamai'
    metrics_path: "/metrics"
    static_configs:
      - targets: ['localhost:8000']  # Assuming your FastAPI app exposes metrics at /metrics on port 8000

  - job_name: 'kafka'
    metrics_path: "/metrics"
    static_configs:
      - targets: ['kafka:9092']  # Ensure Kafka exposes Prometheus metrics or use a Kafka exporter

  - job_name: 'redis'
    metrics_path: "/metrics"
    static_configs:
      - targets: ['redis:6379']  # Ensure Redis exposes Prometheus metrics or use a Redis exporter

  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['kafka_exporter:9308']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']

rule_files:
  - "alerts/alert.rules.yaml"  # Add this line to include alerting rules
